name: Test All Versions(Push)
on:
  push:
    branches:
      - "main"
      - "release/**"
      - "release-please/**"

jobs:
  tav:
    uses: ./.github/workflows/test-all-versions.yml
    with:
      lerna-args: ""
