name: Test All Versions(PR)
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  parse-args:
    runs-on: ubuntu-latest
    container:
      image: node:16
    env:
      PR_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
    outputs:
      args: ${{ steps.lerna-args.outputs.args }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install lerna
        run: npm install -g lerna
      # - name: Install script dependencies
      #   run: npm install --ignore-scripts
      - name: Parse labels into lerna scope arguments
        id: lerna-args
        run: |
          OUTPUT=`node scripts/parse-lerna-scopes.mjs "$PR_LABELS"`
          echo "::set-output name=args::$OUTPUT"

  tav:
    uses: ./.github/workflows/test-all-versions.yml
    needs: parse-args
    with:
      lerna-args: ${{ needs.parse-args.outputs.args }}
    if: ${{ needs.parse-args.outputs.args != '' }}
